### ISSUE TITLE
MAX_INSN_LEN can be too small for 64-bit jmps

### ISSUE THREAD

**Issue by psychonic** [Zeex/subhook#18]
With the newly-added 64-bit jmps, 14 bytes are required. MAX_INSN_LEN is defined as only 15, with trampoline size using the jmp size plus MAX_INSN_LEN - 1 (14).

With needing to end on an instruction boundary, that leaves no extra room for all of the src and jmp bytes in the trampoline. For example, in the example function I posted in #15, 15 bytes are needed for the src instructions that get copied.

**Comment by Zeex** [comment]
I'm not sure I understand what you mean. 

Trampolines consist of the first instruction in src (MAX_INSN_LEN) and a jump whose length is stored in `hook->jmp_size`, so it's `MAX_INSN_LEN + hook->jmp_size` in total.  I can't remember where the `-1` comes from though... 

Sometimes you can't fit the new 64-bit jump code into the `src` because it's very small, e.g. it can be a `jmp` to real implementation (I think DLLs/shared libraries do this a lot). Is this what you mean?

**Comment by Drifter321** [comment]
I believe the issue lies here https://github.com/Zeex/subhook/blob/master/subhook_x86.c#L357. It is being assumed that the length of original bytes is no longer than 14. But as can be seen in the example @psychonic posted, his is longer. The trampoline size should be jmp_size+org_size as noted here https://github.com/Zeex/subhook/blob/master/subhook_x86.c#L334.

On 32 bit its probably unlikely to run into an issue. But for the 64bit the jmp is 14 bytes so if the orignal bytes aren't exactly 14 bytes it gets cut off in the middle of a instruction.

**Comment by Zeex** [comment]
OK, I get it now. Thanks for explaining. I was still thinking in 32-bit mode for some reason.

It seems simple to fix then. I'll give it a try.
